In [1]:
import pathlib
import datetime
import math
import functools
import numpy

In [2]:
import pandas

In [3]:
import iris

In [4]:
import matplotlib

In [5]:
%matplotlib inline

In [72]:
import sklearn
import sklearn.tree
import sklearn.preprocessing
import sklearn.ensemble
import sklearn.neural_network
import sklearn.metrics

In [7]:
# root_data_dir = '/data/users/shaddad/ds_cop/2021_opmet_challenge/ML'
root_data_dir = '/project/informatics_lab/data_science_cop/ML_challenges/2021_opmet_challenge'

## Exploring Falklands Rotor Data

In [8]:
falklands_dir = 'Rotors'
falklands_data_path = pathlib.Path(root_data_dir, falklands_dir)

In [9]:
falklands_new_training_data_path = pathlib.Path(falklands_data_path, 'new_training.csv')

In [10]:
falklands_training_df = pandas.read_csv(falklands_new_training_data_path, header=0).loc[1:,:]
falklands_training_df

DTG  air_temp_obs  dewpoint_obs  wind_direction_obs  \
1      01/01/2015 00:00         283.9         280.7               110.0   
2      01/01/2015 03:00         280.7         279.7                90.0   
3      01/01/2015 06:00         279.8         278.1               100.0   
4      01/01/2015 09:00         279.9         277.0               120.0   
5      01/01/2015 12:00         279.9         277.4               120.0   
...                 ...           ...           ...                 ...   
20101  31/12/2020 06:00         276.7         275.5               270.0   
20102  31/12/2020 09:00         277.9         276.9               270.0   
20103  31/12/2020 12:00         283.5         277.1               220.0   
20104  31/12/2020 15:00         286.1         276.9               250.0   
20105  01/01/2021 00:00         285.1         279.3               300.0   

       wind_speed_obs  wind_gust_obs  air_temp_1  air_temp_2  air_temp_3  \
1                 4.1     -9999999.0     284.000     283.625     283.250   
2                 7.7     -9999999.0     281.500     281.250     280.750   
3                 7.7     -9999999.0     279.875     279.625     279.125   
4                 7.2     -9999999.0     279.625     279.250     278.875   
5                 8.7     -9999999.0     279.250     278.875     278.375   
...               ...            ...         ...         ...         ...   
20101             3.6     -9999999.0     277.875     277.750     277.625   
20102             3.1     -9999999.0     277.875     277.625     277.875   
20103             3.6     -9999999.0     281.125     280.625     280.125   
20104             3.6     -9999999.0     284.625     284.125     283.625   
20105             6.2     -9999999.0     284.250     284.000     283.750   

       air_temp_4  ...  windspd_18  winddir_19  windspd_19  winddir_20  \
1         282.625  ...         5.8       341.0         6.0       334.0   
2         280.250  ...         6.8       344.0         5.3       348.0   
3         278.625  ...         6.0       345.0         5.5       358.0   
4         278.250  ...         3.1       338.0         3.5       354.0   
5         277.875  ...         1.6       273.0         2.0       303.0   
...           ...  ...         ...         ...         ...         ...   
20101     277.500  ...        12.1       223.0        11.8       221.0   
20102     277.875  ...        10.2       230.0        10.8       230.0   
20103     279.625  ...        10.3       218.0        11.9       221.0   
20104     283.000  ...         9.4       218.0         8.6       212.0   
20105     283.250  ...         8.6       241.0        10.2       236.0   

       windspd_20  winddir_21  windspd_21  winddir_22  windspd_22  \
1             6.1       330.0         6.0       329.0         5.8   
2             3.8       360.0         3.2        12.0         3.5   
3             5.0        10.0         4.2        38.0         4.0   
4             3.9         9.0         4.4        22.0         4.6   
5             2.3       329.0         2.5       338.0         2.4   
...           ...         ...         ...         ...         ...   
20101        11.4       219.0        11.3       215.0        11.4   
20102        11.6       227.0        12.3       222.0        12.0   
20103        12.8       222.0        11.9       225.0        10.6   
20104         8.3       218.0         8.7       226.0        10.1   
20105        10.5       232.0        10.5       227.0        11.3   

       Rotors 1 is true  
1                   NaN  
2                   NaN  
3                   NaN  
4                   NaN  
5                   NaN  
...                 ...  
20101               NaN  
20102               NaN  
20103               NaN  
20104               NaN  
20105               NaN  

[20105 rows x 95 columns]

In [11]:
falklands_training_df = falklands_training_df.drop_duplicates(subset='DTG')

In [12]:
falklands_training_df.shape

(17507, 95)

### Specify and create input features

In [45]:
temp_feature_names = [f'air_temp_{i1}' for i1 in range(1,23)]
humidity_feature_names = [f'sh_{i1}' for i1 in range(1,23)]
wind_direction_feature_names = [f'winddir_{i1}' for i1 in range(1,23)]
wind_speed_feature_names = [f'windspd_{i1}' for i1 in range(1,23)]
target_feature_name = 'rotors_present'

In [14]:
def get_v_wind(wind_dir_name, wind_speed_name, row1):
    return math.cos(row1[wind_dir_name]) * row1[wind_speed_name]

def get_u_wind(wind_dir_name, wind_speed_name, row1):
    return math.sin(row1[wind_dir_name]) * row1[wind_speed_name]

In [15]:
u_feature_template = 'u_wind_{level_ix}'
v_feature_template = 'v_wind_{level_ix}'
u_wind_feature_names = []
v_wind_features_names = []
for wsn1, wdn1 in zip(wind_speed_feature_names, wind_direction_feature_names):
    level_ix = int( wsn1.split('_')[1])
    u_feature = u_feature_template.format(level_ix=level_ix)
    u_wind_feature_names += [u_feature]
    falklands_training_df[u_feature_template.format(level_ix=level_ix)] = falklands_training_df.apply(functools.partial(get_u_wind, wdn1, wsn1), axis='columns')
    v_feature = v_feature_template.format(level_ix=level_ix)
    v_wind_features_names += [v_feature]
    falklands_training_df[v_feature_template.format(level_ix=level_ix)] = falklands_training_df.apply(functools.partial(get_v_wind, wdn1, wsn1), axis='columns')

/opt/scitools/environments/experimental/current/lib/python3.6/site-packages/ipykernel/__main__.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/opt/scitools/environments/experimental/current/lib/python3.6/site-packages/ipykernel/__main__.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


In [16]:
falklands_training_df[target_feature_name] =  falklands_training_df['Rotors 1 is true']
falklands_training_df.loc[falklands_training_df[falklands_training_df['Rotors 1 is true'].isna()].index, target_feature_name] = 0.0
falklands_training_df[target_feature_name]  = falklands_training_df[target_feature_name] .astype(bool)

/opt/scitools/environments/experimental/current/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/opt/scitools/environments/experimental/current/lib/python3.6/site-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/opt/scitools/environments/experimental/current/lib/python3.6/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of

In [17]:
falklands_training_df[target_feature_name].value_counts()

False    17058
True       449
Name: rotors_present, dtype: int64

In [18]:
falklands_training_df.columns

Index(['DTG', 'air_temp_obs', 'dewpoint_obs', 'wind_direction_obs',
       'wind_speed_obs', 'wind_gust_obs', 'air_temp_1', 'air_temp_2',
       'air_temp_3', 'air_temp_4',
       ...
       'v_wind_18', 'u_wind_19', 'v_wind_19', 'u_wind_20', 'v_wind_20',
       'u_wind_21', 'v_wind_21', 'u_wind_22', 'v_wind_22', 'rotors_present'],
      dtype='object', length=140)

### SPlit into traing/validate/test sets

In [19]:
test_fraction = 0.1
validation_fraction = 0.1

In [20]:
num_no_rotors = sum(falklands_training_df[target_feature_name] == False)
num_with_rotors = sum(falklands_training_df[target_feature_name] == True)

In [22]:
data_no_rotors = falklands_training_df[falklands_training_df[target_feature_name] == False]
data_with_rotors = falklands_training_df[falklands_training_df[target_feature_name] == True]

In [23]:
data_test = pandas.concat([data_no_rotors.sample(int(test_fraction * num_no_rotors)), data_with_rotors.sample(int(test_fraction * num_with_rotors))])
data_test[target_feature_name].value_counts()

False    1705
True       44
Name: rotors_present, dtype: int64

In [24]:
falklands_training_df['test_set'] = False
falklands_training_df.loc[data_test.index,'test_set'] = True

/opt/scitools/environments/experimental/current/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/opt/scitools/environments/experimental/current/lib/python3.6/site-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)


In [25]:
data_working = falklands_training_df[falklands_training_df['test_set'] == False]
data_working_no_rotors = data_working[data_working[target_feature_name] == False]
data_working_with_rotors = data_working[data_working[target_feature_name] == True]

In [26]:
data_validation = pandas.concat(
    [data_working_no_rotors.sample(int(validation_fraction * num_no_rotors)), 
     data_working_with_rotors.sample(int(validation_fraction * num_with_rotors))])
falklands_training_df['validation_set'] = False
falklands_training_df.loc[data_validation.index,'validation_set'] = True

/opt/scitools/environments/experimental/current/lib/python3.6/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/opt/scitools/environments/experimental/current/lib/python3.6/site-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)


In [27]:
data_validation[target_feature_name].value_counts()

False    1705
True       44
Name: rotors_present, dtype: int64

In [28]:
data_train = falklands_training_df[(~falklands_training_df['test_set']) & (~falklands_training_df['validation_set'])]

In [29]:
data_train[target_feature_name].value_counts()

False    13648
True       361
Name: rotors_present, dtype: int64

# Preprocess data into input for ML algorithm

In [30]:
input_feature_names = temp_feature_names + humidity_feature_names + u_wind_feature_names + v_wind_features_names

In [31]:
preproc_dict = {}
for if1 in input_feature_names:
    scaler1 = sklearn.preprocessing.StandardScaler()
    scaler1.fit(data_train[[if1]])
    preproc_dict[if1] = scaler1

In [40]:
target_encoder = sklearn.preprocessing.LabelEncoder()
target_encoder.fit(data_train[[target_feature_name]])

LabelEncoder()

Apply transformation to each input column

In [46]:
def preproc_input(data_subset, pp_dict):
    return numpy.concatenate([scaler1.transform(data_subset[[if1]]) for if1,scaler1 in pp_dict.items()],axis=1)

def preproc_target(data_subset, enc1):
     return enc1.transform(data_subset[[target_feature_name]])

In [33]:
X_train = preproc_input(data_train, preproc_dict)
y_train = preproc_target(data_train, target_encoder)

create target feature from rotors

In [48]:
y_train.shape, X_train.shape

((14009,), (14009, 88))

### train some classifiers

In [133]:
classifiers_dict = {
    'decision_tree': sklearn.tree.DecisionTreeClassifier(max_depth=10, class_weight='balanced'),
    'random_forest': sklearn.ensemble.RandomForestClassifier(max_depth=10, class_weight='balanced'),
#      'ann': sklearn.neural_network.MLPClassifier(),
}                    


In [134]:
%%time
for clf_name, clf1 in classifiers_dict.items():
    print(clf_name)
    clf1.fit(X_train, y_train)

decision_tree
random_forest
CPU times: user 5.78 s, sys: 0 ns, total: 5.78 s
Wall time: 5.81 s


In [135]:
X_val = preproc_input(data_validation, preproc_dict)
y_val = preproc_target(data_validation, target_encoder)

/opt/scitools/environments/experimental/current/lib/python3.6/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [136]:
X_test = preproc_input(data_test, preproc_dict)
y_test = preproc_target(data_test, target_encoder)

/opt/scitools/environments/experimental/current/lib/python3.6/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [137]:
for clf_name, clf1 in classifiers_dict.items():
    print(sklearn.metrics.precision_recall_fscore_support(clf1.predict(X_train), y_train))
    print(sklearn.metrics.precision_recall_fscore_support(clf1.predict(X_val), y_val))
    print(sklearn.metrics.precision_recall_fscore_support(clf1.predict(X_test), y_test))

(array([0.86628077, 0.99168975]), array([0.99974632, 0.1639945 ]), array([0.92824056, 0.28144654]), array([11826,  2183]))
(array([0.86686217, 0.56818182]), array([0.98730795, 0.09920635]), array([0.92317302, 0.16891892]), array([1497,  252]))
(array([0.87096774, 0.61363636]), array([0.98868176, 0.10931174]), array([0.92609916, 0.18556701]), array([1502,  247]))
(array([0.94482708, 1.        ]), array([1.        , 0.32405745]), array([0.97163094, 0.48949153]), array([12895,  1114]))
(array([0.94252199, 0.38636364]), array([0.98347613, 0.14782609]), array([0.96256364, 0.21383648]), array([1634,  115]))
(array([0.94076246, 0.5       ]), array([0.98646986, 0.17886179]), array([0.96307415, 0.26347305]), array([1626,  123]))


In [74]:
sklearn.metrics.confusion_matrix(classifiers_dict['decision_tree'].predict(X_train), y_train)

array([[13648,     0],
       [    0,   361]])

In [73]:
sklearn.metrics.confusion_matrix(classifiers_dict['decision_tree'].predict(X_val), y_val)

array([[1653,   32],
       [  52,   12]])

In [75]:
sklearn.metrics.confusion_matrix(classifiers_dict['random_forest'].predict(X_val), y_val)

array([[1705,   44],
       [   0,    0]])

In [118]:
data_train_resampled = pandas.concat([
    data_train[data_train[target_feature_name] == True].sample(n=int(1e4), replace=True), 
    data_train[data_train[target_feature_name] == False].sample(n=int(1e4), replace=False),],
    ignore_index=True)

In [129]:
classifiers_res_dict = {
    'decision_tree': sklearn.tree.DecisionTreeClassifier(max_depth=10, class_weight='balanced'),
#     'random_forest': sklearn.ensemble.RandomForestClassifier(),
#      'ann': sklearn.neural_network.MLPClassifier(),
}                    


In [121]:
X_train_resampled = preproc_input(data_train_resampled, preproc_dict)
y_train_resampled = preproc_target(data_train_resampled, target_encoder)

/opt/scitools/environments/experimental/current/lib/python3.6/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [122]:
%%time
for clf_name, clf1 in classifiers_res_dict.items():
    print(clf_name)
    clf1.fit(X_train_resampled, y_train_resampled)
    

decision_tree
CPU times: user 1.21 s, sys: 2.38 ms, total: 1.22 s
Wall time: 1.22 s


In [127]:
for clf_name, clf1 in classifiers_res_dict.items():
    print(sklearn.metrics.precision_recall_fscore_support(clf1.predict(X_train_resampled), y_train_resampled))
    print(sklearn.metrics.precision_recall_fscore_support(clf1.predict(X_val), y_val))
    print(sklearn.metrics.precision_recall_fscore_support(clf1.predict(X_test), y_test))

(array([1., 1.]), array([1., 1.]), array([1., 1.]), array([10000, 10000]))
(array([0.97067449, 0.04545455]), array([0.97525044, 0.03846154]), array([0.97295708, 0.04166667]), array([1697,   52]))
(array([0.97653959, 0.06818182]), array([0.97596717, 0.06976744]), array([0.9762533 , 0.06896552]), array([1706,   43]))


In [128]:
for clf_name, clf1 in classifiers_res_dict.items():
    print(sklearn.metrics.balanced_accuracy_score(clf1.predict(X_train_resampled), y_train_resampled))
    print(sklearn.metrics.balanced_accuracy_score(clf1.predict(X_val), y_val))
    print(sklearn.metrics.balanced_accuracy_score(clf1.predict(X_test), y_test))    


1.0
0.5068559902089661
0.5228673082690367
